---
title: "data_import"
author: "Arghya Kannadaguli (ak5357)"
date: "2025-02-18"
output: html_document
---
```{r}
# Data manipulation
library(tidyverse)
library(dplyr)
library(gtsummary)
library(gt)

# Modeling
library(glmnet)
library(caret)
library(tidymodels)

# Plotting
library(ggplot2)
library(plotmo)
library(ggrepel)
```

## **Import and Clean All Data**

```{r}
# Cal Enviro Screen 4.0 Dataset
cal.enviro = 
  readxl::read_excel(
    "data/calenviroscreen40resultsdatadictionary_f_2021.xlsx",
    sheet = 1, na = c("NA")) |> 
  janitor::clean_names() |> 
  select(census_tract, approximate_location, zip, california_county, latitude, longitude, drinking_water, low_birth_weight) |> 
  rename(geo_id = census_tract, city = approximate_location) |> 
  arrange(geo_id) |> 
  mutate(geo_id = as.character(ifelse(geo_id == 6037930401, 6037137000, geo_id)))

# ACS Economic Data
acs.ses = read_csv("data/ACS_ses_Data.csv",
    na = c("(X)", "N", "*", "**", "-")) |> 
  janitor::clean_names()

# ACS Social Data
acs.soc = read_csv("data/ACS_social_Data.csv",
    na = c("(X)", "N", "*", "**", "-")) |> 
  janitor::clean_names()

# All ACS Data
acs.raw = full_join(acs.ses, acs.soc, by = "geo_id")
acs = acs.raw |> 
  select(
    "geo_id",
    "percent_employment_status_females_16_years_and_over_in_labor_force",
    "percent_employment_status_civilian_labor_force_unemployment_rate",
    "percent_health_insurance_coverage_civilian_noninstitutionalized_population_with_health_insurance_coverage",
    "percent_disability_status_of_the_civilian_noninstitutionalized_population_total_civilian_noninstitutionalized_population_with_a_disability",
    "estimate_income_and_benefits_in_2015_inflation_adjusted_dollars_total_households_median_household_income_dollars",
    "percent_percentage_of_families_and_people_whose_income_in_the_past_12_months_is_below_the_poverty_level_all_families",
    "percent_percentage_of_families_and_people_whose_income_in_the_past_12_months_is_below_the_poverty_level_all_people",
    "percent_residence_1_year_ago_population_1_year_and_over_same_house",
    starts_with("percent_educational_attainment"),
    starts_with("percent_marital_status_female"),
    "percent_place_of_birth_total_population_foreign_born",
    starts_with("percent_world"),
    "percent_u_s_citizenship_status_foreign_born_population_not_a_u_s_citizen",
    starts_with("percent_language") & contains("english_less"),
    -c("percent_marital_status_females_15_years_and_over",
       "percent_educational_attainment_population_25_years_and_over",
       "percent_world_region_of_birth_of_foreign_born_foreign_born_population_excluding_population_born_at_sea")
    ) |> 
  rename(
    # Employment
    female_employment_rate = percent_employment_status_females_16_years_and_over_in_labor_force,
    unemployment_rate = percent_employment_status_civilian_labor_force_unemployment_rate,
    
    # Health
    health_insurance_coverage = percent_health_insurance_coverage_civilian_noninstitutionalized_population_with_health_insurance_coverage,
    disability = percent_disability_status_of_the_civilian_noninstitutionalized_population_total_civilian_noninstitutionalized_population_with_a_disability,
    
    # Poverty
    median_income = estimate_income_and_benefits_in_2015_inflation_adjusted_dollars_total_households_median_household_income_dollars,
    poverty_rate_families = percent_percentage_of_families_and_people_whose_income_in_the_past_12_months_is_below_the_poverty_level_all_families,
    poverty_rate_all = percent_percentage_of_families_and_people_whose_income_in_the_past_12_months_is_below_the_poverty_level_all_people,
    residence_over_1y = percent_residence_1_year_ago_population_1_year_and_over_same_house, # low may indicate high residence turnover
    
    # Education
    edu_less_than_hs = percent_educational_attainment_population_25_years_and_over_less_than_9th_grade,
    edu_some_hs = percent_educational_attainment_population_25_years_and_over_9th_to_12th_grade_no_diploma,
    edu_hs = percent_educational_attainment_population_25_years_and_over_high_school_graduate_includes_equivalency,
    edu_some_college = percent_educational_attainment_population_25_years_and_over_some_college_no_degree,
    edu_associate = percent_educational_attainment_population_25_years_and_over_associates_degree,
    edu_bachelors = percent_educational_attainment_population_25_years_and_over_bachelors_degree,
    edu_grad_prof = percent_educational_attainment_population_25_years_and_over_graduate_or_professional_degree,
    edu_hs_or_higher = percent_educational_attainment_percent_high_school_graduate_or_higher,
    edu_bachelors_or_higher = percent_educational_attainment_percent_bachelors_degree_or_higher,
    
    # Female Marital Status
    fms_never_married = percent_marital_status_females_15_years_and_over_never_married,
    fms_married_separated = percent_marital_status_females_15_years_and_over_now_married_except_separated,
    fms_separated = percent_marital_status_females_15_years_and_over_separated,
    fms_widowed = percent_marital_status_females_15_years_and_over_widowed,
    fms_divorced = percent_marital_status_females_15_years_and_over_divorced,
    
    # Foreign Born and Origin
    foreign_born = percent_place_of_birth_total_population_foreign_born,
    foreign_born_not_citizen = percent_u_s_citizenship_status_foreign_born_population_not_a_u_s_citizen,
    foreign_born_europe = percent_world_region_of_birth_of_foreign_born_foreign_born_population_excluding_population_born_at_sea_europe,
    foreign_born_asia = percent_world_region_of_birth_of_foreign_born_foreign_born_population_excluding_population_born_at_sea_asia,
    foreign_born_africa = percent_world_region_of_birth_of_foreign_born_foreign_born_population_excluding_population_born_at_sea_africa,
    foreign_born_oceania = percent_world_region_of_birth_of_foreign_born_foreign_born_population_excluding_population_born_at_sea_oceania,
    foreign_born_latin_america = percent_world_region_of_birth_of_foreign_born_foreign_born_population_excluding_population_born_at_sea_latin_america,
    foreign_born_north_america = percent_world_region_of_birth_of_foreign_born_foreign_born_population_excluding_population_born_at_sea_northern_america,
    
    # Linguistic Isolation
    limited_english = percent_language_spoken_at_home_population_5_years_and_over_language_other_than_english_speak_english_less_than_very_well,
    limited_english_spanish = percent_language_spoken_at_home_population_5_years_and_over_spanish_speak_english_less_than_very_well,
    limited_english_indo_euro = percent_language_spoken_at_home_population_5_years_and_over_other_indo_european_languages_speak_english_less_than_very_well,
    limited_english_aapi = percent_language_spoken_at_home_population_5_years_and_over_asian_and_pacific_islander_languages_speak_english_less_than_very_well,
    limited_english_other = percent_language_spoken_at_home_population_5_years_and_over_other_languages_speak_english_less_than_very_well) |> 
  arrange(geo_id) |> 
  mutate(geo_id = str_remove(geo_id, "[01]400000US0")) |> 
  filter(geo_id != "6")

# Maternal Ages at Birth
mat.age = read_csv("data/mother_clean.csv") |> 
  arrange(geo_id) |> 
  mutate(
    geo_id = str_remove(geo_id, "1400000US0"),
    birth_dif = total_birth - (birth_15_19 + birth_20_24 + birth_25_29 + birth_30_34 + birth_35_39 + birth_40_44 + birth_45_50),
    total_birth = (birth_15_19 + birth_20_24 + birth_25_29 + birth_30_34 + birth_35_39 + birth_40_44 + birth_45_50),
    birthing_rate = ifelse(total > 0, 100*total_birth / total, 0), # percent of people able to give birth who actually gave birth
    avg_birthing_age = ifelse(total_birth > 0, (17*birth_15_19 + 22*birth_20_24 + 27*birth_25_29 + 32*birth_30_34 + 37*birth_35_39 + 42*birth_40_44 + 47.5*birth_45_50) / total_birth, NA_real_),
    teen_birth = ifelse(total_birth>0, birth_15_19 / total_birth, NA_real_),
    geriatric_birth = ifelse(total_birth>0, (birth_35_39 + birth_40_44 + birth_45_50) / total_birth, NA_real_)
  ) |> 
  rename(total_birth_pop = total, total_birth_count = total_birth) |> 
  select(geo_id, total_birth_pop, total_birth_count, birthing_rate, avg_birthing_age, teen_birth, geriatric_birth)
```

## **Join All Data**

```{r}
dat.raw = cal.enviro |> 
  full_join(mat.age, by = "geo_id") |> 
  full_join(acs, by = "geo_id")
```

## **Explore Missing Values**

```{r}
dat.test = dat.raw |> 
  mutate(
    birth_data = factor(case_when(
      total_birth_pop == 0 ~ "Birth Pop = 0, Birth Count = 0",
      total_birth_count == 0 ~ "Birth Pop > 0, Birth Count = 0",
      total_birth_pop > 0 & total_birth_count > 0 ~ "Birth Pop > 0, Birth Count > 0"
    )),
    missing = factor(case_when(
      is.na(city) ~ "Missing all CalEnviro\n& ACS data",
      is.na(low_birth_weight) & is.na(drinking_water) ~ "Both",
      is.na(low_birth_weight) ~ "LBW",
      is.na(drinking_water) ~ "DWC",
      TRUE ~ "None"), levels = c("Both", "DWC", "LBW", "None", "Missing all CalEnviro\n& ACS data")),
    exclusion_criteria = case_when(
      total_birth_pop == 0 & is.na(city) ~ "(X) Birth Pop 0 & missing Cal/ACS",
      total_birth_pop == 0 & missing == "Both" ~ "(X) Birth Pop = 0 & missing DWC/LBW",
      total_birth_pop == 0 & missing == "LBW" ~ "(X) Birth Pop = 0 & missing only LBW",
      total_birth_pop == 0 ~ "(?) Birth Pop = 0 but & no missing data",
      total_birth_pop > 0 & total_birth_count == 0 & missing != "None" ~ "(?) Birth Pop > 0, Count = 0 & missing data",
      total_birth_pop > 0 & total_birth_count == 0 & missing == "None" ~ "(?) Birth Pop> 0, Count = 0 & no missing data",
      total_birth_count > 0 & missing != "None" ~ "(?) Birth Count > 0 & missing data",
      total_birth_count > 0 & missing == "None" ~ "(I) Birth Count > 0 & no missing data",
      TRUE ~ paste(missing, birth_data)),
    exclude = case_when(
      total_birth_pop == 0 & is.na(city) ~ "Exclude",
      total_birth_pop == 0 & missing == "Both" ~ "Exclude",
      total_birth_pop == 0 & missing == "LBW" ~ "Exclude",
      total_birth_pop == 0 ~ "?",
      total_birth_pop > 0 & total_birth_count == 0 ~ "?",
      total_birth_count > 0 & missing != "None" ~ "?",
      total_birth_count > 0 & missing == "None" ~ "Include",
      TRUE ~ "?"))

dat.test |> 
  filter(total_birth_pop > 0 & total_birth_count > 0 & missing == "None") |> 
  nrow()

dat.test |> 
  count(exclude, exclusion_criteria)

library(maps)
states.map = map_data("state")
ca.map = states.map |> filter(region == "california")

# Map by Outcome Missingness
dat.test1 = dat.raw |> 
  mutate(
    birth_data = factor(case_when(
      total_birth_pop == 0 ~ "Birth Pop = 0, Birth Count = 0",
      total_birth_count == 0 ~ "Birth Pop > 0, Birth Count = 0",
      total_birth_pop > 0 & total_birth_count > 0 ~ "Birth Pop > 0, Birth Count > 0"
    )),
    missing = factor(case_when(
      is.na(city) ~ "Missing all CalEnviro\n& ACS data",
      is.na(low_birth_weight) ~ "LBW",
      TRUE ~ "None"), levels = c("LBW", "None", "Missing all CalEnviro\n& ACS data")))


# Map by exposure / outcome missingness
dat.test |> 
  filter(missing != "Missing all CalEnviro\n& ACS data") |> 
  ggplot(aes(x = longitude, y = latitude, color = missing)) +
  geom_polygon(data = ca.map, aes(x = long, y = lat, group = group), 
               fill = "grey95", color = "grey", alpha = 0.6) +
  geom_point(alpha = 0.7) +
  scale_color_brewer(palette = "Spectral") +
  facet_wrap(~ missing) + 
  theme_classic() +
  labs(
    title = "Spatial distribution of missing exposure and outcome data",
    x = "", y = "",
    subtitle = "Not depicting the 22 tracts missing all CalEnviro and ACS data"
  )

# Map by birth data genre
dat.test |> 
  ggplot(aes(x = longitude, y = latitude, color = birth_data)) +
  geom_polygon(data = ca.map, aes(x = long, y = lat, group = group), 
               fill = "grey95", color = "grey", alpha = 0.6) +
  geom_point(alpha = 0.7) +
  scale_color_brewer(palette = "Paired") +
  facet_wrap(~ birth_data, nrow = 2) + 
  theme_classic() +
  labs(
    title = "Spatial distribution of birthing population and births",
    x = "", y = "",
    subtitle = "2011-2015 Maternal Data"
  )

# Barplot of missingness types by birth data genre
dat.test |> 
  count(birth_data, missing) |> 
  mutate(pct_of_tracts = 100*(n/nrow(dat.raw))) |> 
  ggplot(aes(x = missing, y = n, fill = missing)) +
  geom_bar(stat = "identity") +
  scale_fill_brewer(palette = "Spectral") + 
  facet_wrap(~ birth_data, scale = "free_y") +
  geom_text(aes(label = n), size = 3, vjust = -0.5) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))

# Proposal for exclusion criteria
dat.test |> 
  ggplot(aes(x = longitude, y = latitude, color = exclude)) +
  geom_polygon(data = ca.map, aes(x = long, y = lat, group = group), 
               fill = "grey95", color = "grey", alpha = 0.6) +
  scale_color_manual(values = c("?" = "yellow", "Exclude" = "darkred", "Include" = "darkgreen")) +
  geom_point(alpha = 0.7) +
  facet_wrap(~ exclusion_criteria, nrow = 2) + 
  theme_classic() +
  labs(
    title = "Exclusion Criteria Proposal",
    x = "", y = "",
    subtitle = "2011-2015 Maternal Data"
  )

```

```{r}
dat = dat.raw |> 
  filter(!is.na(low_birth_weight) & total_birth_pop & total_birth_count > 0) |> 
  drop_na()

dat.raw |> nrow()
dat |> nrow()

nrow(dat)

dat |> 
  filter(is.na(median_income))

problem_tracts = dat$geo_id[is.na(dat$median_income)]

dat.raw[dat.raw$geo_id %in% c("6037700700", "6065044521", "6075980600", "6081611500"),]

lm(foreign_born ~ limited_english, data = dat)
corr.test(dat$foreign_born, dat$limited_english)


# Check for Null Values across columns
dat |>
  # filter(!is.na(drinking_water) & !is.na(low_birth_weight) & total_birth_pop > 0 & total_birth_count > 0) |>
  lapply(is.na) |>
  lapply(sum) |>
  as_tibble() |>
  pivot_longer(everything(), names_to = "col", values_to = "na_count") |>
  filter(na_count > 0)

dat |> 
  filter(california_county == "Los Angeles") |> 
  nrow()

dat |> glimpse()
```

## **Export Dataframe**

```{r}
write_csv(dat, "data/AAMEHS Final Dataset.csv")
```


